### ISSUE TITLE
HHVM support for Composer Script Handler

### ISSUE THREAD

**Issue by chasen** [braincrafted/bootstrap-bundle#306]
It seem that in order to support hhvm some changes need to be made to the script handler. For reference https://github.com/sensiolabs/SensioDistributionBundle/pull/150/files. But im not 100% sure what is needed or I would create a PR myself.

````
sh: 1: /usr/bin/hhvm --php: not found
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap handling the post-install-cmd event terminated with an exception

  [RuntimeException]
  An error occurred when generating the bootstrap file.
````

**Comment by eddiejaoude** [comment]
I have the same issue...

```php
sh: 1: /usr/bin/hhvm --php: not found
Script Braincrafted\Bundle\BootstrapBundle\Composer\ScriptHandler::install handling the post-install-cmd event terminated with an exception
                                                                               
  [RuntimeException]                                                           
  An error occurred when executing the "'braincrafted:bootstrap:install'" com  
  mand.         
```

TravisCI Reference: https://travis-ci.org/eddiejaoude/SymfonyQuickStart/jobs/50962050#L368 

Any moment on this?

**Comment by florianeckerstorfer** [comment]
As mentioned above the Composer ScriptHandler is not required. You can copy the fonts into the web directory manually (or using a line of Bash in your build process).

**Comment by eddiejaoude** [comment]
ok thanks.

**Comment by Sydney-o9** [comment]
That's not fixed people

````
sh: /usr/local/hhvm/hphp/hhvm/hhvm --php: No such file or directory
Script Braincrafted\Bundle\BootstrapBundle\Composer\ScriptHandler::install handling the post-update-cmd event terminated with an exception

  [RuntimeException]
  An error occurred when executing the "'braincrafted:bootstrap:install'" command.
````

**Comment by florianeckerstorfer** [comment]
Is `/usr/local/hhvm/hphp/hhvm/hhvm` the correct path to HHVM?

**Comment by Sydney-o9** [comment]
@florianeckerstorfer yes it is

**Comment by Sydney-o9** [comment]
That's the actual error - might be easier to debug:

<img width="633" alt="screen shot 2015-08-26 at 4 52 39 pm" src="https://cloud.githubusercontent.com/assets/1480617/9487233/17a8da9c-4c13-11e5-80fb-52132a331575.png">

**Comment by dimkir** [comment]
@Sydney-o9 Actuall the fix mentioned above works (at least on `ubuntu 14.04` with `HHVM 3.1`). 

I think the problem is that most people would use version constraint `^2.1` or similar (for compatability with latest bootstrap and symfony). eg.: 
```json
  "braincrafted/bootstrap-bundle": "^2.1",
```

but the latest tag on the repo is `2.1.2` and this tag is way behind `develop` branch into which the HHVM fix was merged. 

@Sydney-o9  Please check which version of bundle `composer show -i | grep brain` you're using and if not maybe you need to specify 
```json
  "braincrafted/bootstrap-bundle": "dev-develop",
```
   or if you don't want to depend on ever-moving develop branch you can depend on where it points today

```json
  "braincrafted/bootstrap-bundle": "dev-develop#20cffee",
```

@florianeckerstorfer would it be possible to get a next tagged release anytime soon?
