### ISSUE TITLE
Bootstrap 4.0 support?

### ISSUE THREAD

**Issue by andrewtch** [braincrafted/bootstrap-bundle#390]
Is it planned?

**Comment by florianeckerstorfer** [comment]
At the moment this looks not good, since I am currently not using BootstrapBundle in any active project and can't justify spending a lot of time on it. However, if someone is willing to contribute the required code  and would make that person maintainer of the 4.0 version. Or the person forks the project, whatever she or he likes best.

**Comment by andrewtch** [comment]
Unfortunately I've dropped all the bundles myself and sticked to plain old bower installation w/ custom from_theme. Closing then for now.
